service: bpk-lambda-function

provider:
  name: aws
  runtime: python3.8

# you can overwrite defaults here
#  stage: dev
  region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"

# you can add packaging information here
package:
  include:
    - ../code/**
  exclude:
    - node_modules/**
    - ./*.json

functions:
  hello:
    handler: code/handle.lambda_handler
